services:
  - type: web
    name: backend-service
    runtime: node
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase: minha-database